# Generated by Django 6.1 on 2026-08-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('college', 'College / University'), ('manufacturing', 'Manufacturing / Textile')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('emails', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
