# Generated by Django 6.1 on 2026-08-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='batch_id',
        ),
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='emails',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='website',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
