# Generated by Django 6.1 on 2026-08-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_lead_batch_id_alter_lead_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='category',
        ),
    ]
